### ISSUE TITLE
APK loaded but no game

### ISSUE THREAD

**Issue by Fenyx4** [plaidpants/ANHK-VR#10]
![black](https://github.com/plaidpants/ANKH-VR/assets/2976266/cbf2c781-99a1-42a4-b8aa-73d3c4dcea1e)

Not sure if I am doing something wrong but I was able to sideload the new apk file but when I loaded it I just got the above screen.

I sideloaded with SideQuest onto my Quest 3 (yeah, Facebook evil but I had extenuating circumstanced 😄  ).

**Comment by plaidpants** [comment]
I get this screen also if I have not installed the ultima 4 DOS files into the /sdcard/Android/data/com.SwivelChairGames.ANKHVR/files/u4/ on the quest. make sure you have them installed in the right place.

**Comment by plaidpants** [comment]
Remember Android is case sensitive unlike the PC

**Comment by plaidpants** [comment]
You can run this command to check and see what files are there and the permissions. I noticed that SideQuest did not copy all the files when I did a test transfer so double check they all got there.
adb shell ls -la /sdcard/Android/data/com.SwivelChairGames.ANKHVR/files/u4/

FYI this means it is Read only for everyone but the OS
-rw-**r-**-r-- 1 shell ext_data_rw 512 2024-02-01 09:17 /sdcard/Android/data/com.SwivelChairGames.ANKHVR/files/u4/DNGMAP.SAV
This means it is read write for the app
-rw-**rw**-r-- 1 shell ext_data_rw 512 2024-02-01 09:17 /sdcard/Android/data/com.SwivelChairGames.ANKHVR/files/u4/DNGMAP.SAV

**Comment by plaidpants** [comment]
BTW, how much do you add for your sacrifice fix, giving blood adds 5 sacrifice but giving a coin only adds 2 compassion, should I add 2 or 5 for giving your last coin

**Comment by plaidpants** [comment]
Found it, the answer is 3

**Comment by Fenyx4** [comment]
Doh. Sorry, completely missed the step to copy those files to my quest. I will give that a try tomorrow.

Yup 3. Sorry I didn't see your question sooner.

**Comment by plaidpants** [comment]
Sounds good, yes, literally everything in the game comes from the u4 PC game files, nothing is in the APK, Richard G. was going to try it out this weekend also with his family. Hopefully he won't run into to many bugs. On the plus side I discovered a file transfer bug in SideQuest that they will now need to fix.

**Comment by Fenyx4** [comment]
When I loaded up the files things worked!
Thanks.

RG is going to play it!?! That is awesome! Congrats!

**Comment by plaidpants** [comment]
not an issue but there is an issue with SideQuest when copying multiple files with the same names but in different directories, SideQuest will only copy the first instance it finds of those files, so for example if you have a set of .SAV files in a folder called backup and the same set of file in the parent directory, it will only copy the files in the backup folder and not the files in the parent directory. So you need to be careful everything got copied when you drag an drop a bunch of files and folders to your quest.
