### ISSUE TITLE
Missing spaces (or maybe end lines?) when talking to reagent seller

### ISSUE THREAD

**Issue by Fenyx4** [plaidpants/ANHK-VR#13]
![unnamed](https://github.com/plaidpants/ANKH-VR/assets/2976266/b5adf942-877f-4a3a-8110-9bd4dd81754a)

**Comment by plaidpants** [comment]
I had fixed these issues manually before, but now that I am using the vanilla text from AVATAR.EXE directly, I will have to add additional formatting to get around these text flow issues.

**Comment by plaidpants** [comment]
fixed
